sources:
  - name: VentureBeat AI
    rss: "https://venturebeat.com/category/ai/feed/"
    url: ""
    articles_per_day: 3
  - name: TechCrunch AI
    rss: "https://techcrunch.com/category/artificial-intelligence/feed/"
    url: ""
    articles_per_day: 3
  - name: MarkTechPost
    rss: "https://www.marktechpost.com/feed/"
    url: ""
    articles_per_day: 2
  - name: ScienceDaily AI
    rss: "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml"
    url: ""
    articles_per_day: 2
  - name: MIT Tech Review AI
    rss: "https://www.technologyreview.com/topic/artificial-intelligence/feed/"
    url: ""
    articles_per_day: 1
  - name: The Rundown AI
    rss: "https://www.therundown.ai/feed"
    url: ""
    articles_per_day: 1
  - name: 量子位 QbitAI
    rss: ""
    url: "https://www.qbitai.com/"
    articles_per_day: 3
    selectors:
      article_link: "h3 a, .post-title a, .entry-title a, a.post-title, a[href*='/p/']"
      title: "h1.entry-title, h1.post-title, h1, .article-title"
      body: "article, .entry-content, .post-content, .content"
      image: "article img, .entry-content img, .post-content img, .content img"
  - name: 机器之心 Synced
    rss: ""
    url: "https://www.jiqizhixin.com/"
    articles_per_day: 3
    selectors:
      article_link: "a[href*='/articles/']"
      title: "h1.article-title, h1.post-title, h1"
      body: "article, .content, .content-detail, .article-content"
      image: "article img, .content img, .content-detail img, .article-content img"
  - name: 智东西 Zhidx
    rss: ""
    url: "https://www.zhidx.com/"
    articles_per_day: 2
    selectors:
      article_link: "a[href*='/p/']"
      title: "h1.article-title, h1.post-title, h1"
      body: "article, .content, .post-content, .article-content"
      image: "article img, .content img, .post-content img, .article-content img"
